# Generated by Django 3.1.7 on 2021-03-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='player_profile_pic'),
        ),
    ]
